//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttentionalProcessing_OT2
    {
        public int AttentionalProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string RG_76 { get; set; }
        public string SN_77 { get; set; }
        public string SN_78 { get; set; }
        public string RG_79 { get; set; }
        public string RG_80 { get; set; }
        public string AV_81 { get; set; }
        public string SK_82 { get; set; }
        public string SK_83 { get; set; }
        public string SN_84 { get; set; }
        public string RG_85 { get; set; }
        public string RG_86 { get; set; }
        public Nullable<int> Attentional_Score { get; set; }
        public string Attentional_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
