//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoryProcessing_OT2
    {
        public int AuditoryProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string AV_1 { get; set; }
        public string AV_2 { get; set; }
        public string SN_3 { get; set; }
        public string SN_4 { get; set; }
        public string AV_5 { get; set; }
        public string SN_6 { get; set; }
        public string SN_7 { get; set; }
        public string RG_8 { get; set; }
        public Nullable<int> Auditory_Raw_Score { get; set; }
        public string Auditory_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
