//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avoiding_OT2
    {
        public int AvoidingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string Raw_Score_1 { get; set; }
        public string Raw_Score_2 { get; set; }
        public string Raw_Score_5 { get; set; }
        public string Raw_Score_15 { get; set; }
        public string Raw_Score_18 { get; set; }
        public string Raw_Score_58 { get; set; }
        public string Raw_Score_59 { get; set; }
        public string Raw_Score_61 { get; set; }
        public string Raw_Score_63 { get; set; }
        public string Raw_Score_64 { get; set; }
        public string Raw_Score_65 { get; set; }
        public string Raw_Score_66 { get; set; }
        public string Raw_Score_67 { get; set; }
        public string Raw_Score_68 { get; set; }
        public string Raw_Score_70 { get; set; }
        public string Raw_Score_71 { get; set; }
        public string Raw_Score_72 { get; set; }
        public string Raw_Score_74 { get; set; }
        public string Raw_Score_75 { get; set; }
        public string Raw_Score_81 { get; set; }
        public Nullable<int> Avoiding_Score { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
