//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConductProcessing_OT2
    {
        public int ConductProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string RG_53 { get; set; }
        public string RG_54 { get; set; }
        public string SK_55 { get; set; }
        public string SK_56 { get; set; }
        public string RG_57 { get; set; }
        public string AV_58 { get; set; }
        public string AV_59 { get; set; }
        public string SK_60 { get; set; }
        public string AV_61 { get; set; }
        public Nullable<int> Conduct_Raw_Score { get; set; }
        public string Conduct_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
