//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryPregnancy_PT
    {
        public int HistoryPregnancyPT_ID { get; set; }
        public int PT_ID { get; set; }
        public string Pregnancy_Length { get; set; }
        public string Pregnancy_Type { get; set; }
        public string Birth_Detail { get; set; }
        public string Breathing_Problem { get; set; }
        public string Baby_Position { get; set; }
        public string Pregnancy { get; set; }
    
        public virtual Physiotherapy Physiotherapy { get; set; }
    }
}
