//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalInformation_PT
    {
        public int MedicalInformationPT_ID { get; set; }
        public int PT_ID { get; set; }
        public string Name_Of_Gp { get; set; }
        public string Medication { get; set; }
        public string Illness { get; set; }
        public string Allergies { get; set; }
        public string Tests { get; set; }
        public string Surgical_Intervention { get; set; }
    
        public virtual Physiotherapy Physiotherapy { get; set; }
    }
}
