//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingInformation_IEP
    {
        public int MeetingInformation_ID { get; set; }
        public int IEPlan_ID { get; set; }
        public Nullable<bool> Initial_IEP { get; set; }
        public Nullable<System.DateTime> Date_Initial_IEP { get; set; }
        public Nullable<bool> Annual_Review { get; set; }
        public Nullable<System.DateTime> Date_Annual_Review { get; set; }
        public Nullable<bool> Review_Other_Than_Annaul_Review { get; set; }
        public Nullable<System.DateTime> Date_Review_Other_Than_Annaul_Review { get; set; }
        public Nullable<bool> Ammendment { get; set; }
        public Nullable<System.DateTime> Date_Ammendment { get; set; }
        public string Communicating_Language { get; set; }
    
        public virtual IEPlan IEPlan { get; set; }
    }
}
