//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone_PT
    {
        public int MilestonePT_ID { get; set; }
        public int PT_ID { get; set; }
        public string Cry { get; set; }
        public string Neck_Control { get; set; }
        public string Sitting { get; set; }
        public string Crawling { get; set; }
        public string Standing { get; set; }
        public string Walking { get; set; }
        public string Spoke_First_Word { get; set; }
        public string Bowl_Bladder { get; set; }
        public string Tactile { get; set; }
        public string Auditory { get; set; }
        public string Visual { get; set; }
        public string Taste_Smell { get; set; }
    
        public virtual Physiotherapy Physiotherapy { get; set; }
    }
}
