//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationalTherapy2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OccupationalTherapy2()
        {
            this.AttentionalProcessing_OT2 = new HashSet<AttentionalProcessing_OT2>();
            this.AuditoryProcessing_OT2 = new HashSet<AuditoryProcessing_OT2>();
            this.Avoiding_OT2 = new HashSet<Avoiding_OT2>();
            this.BodyPositionProcessing_OT2 = new HashSet<BodyPositionProcessing_OT2>();
            this.ConductProcessing_OT2 = new HashSet<ConductProcessing_OT2>();
            this.MovementProcessing_OT2 = new HashSet<MovementProcessing_OT2>();
            this.OralSensoryProcessing_OT2 = new HashSet<OralSensoryProcessing_OT2>();
            this.Registration_OT2 = new HashSet<Registration_OT2>();
            this.Seeking_OT2 = new HashSet<Seeking_OT2>();
            this.Sensitivity_OT2 = new HashSet<Sensitivity_OT2>();
            this.SocialEmotionalProcessing_OT2 = new HashSet<SocialEmotionalProcessing_OT2>();
            this.TouchProcessing_OT2 = new HashSet<TouchProcessing_OT2>();
            this.VisualProcessing_OT2 = new HashSet<VisualProcessing_OT2>();
        }
    
        public int OT2_ID { get; set; }
        public int GR_NO { get; set; }
        public Nullable<System.DateTime> Test_Date { get; set; }
        public string Examiner_Name { get; set; }
        public string Examiner_Profession { get; set; }
        public string Caregiver_Name { get; set; }
        public string Caregiver_Relationship { get; set; }
        public string Name_Of_School { get; set; }
        public Nullable<int> School_Level { get; set; }
        public string Child_Order { get; set; }
        public string Children_Years_Living { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttentionalProcessing_OT2> AttentionalProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoryProcessing_OT2> AuditoryProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avoiding_OT2> Avoiding_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyPositionProcessing_OT2> BodyPositionProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConductProcessing_OT2> ConductProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementProcessing_OT2> MovementProcessing_OT2 { get; set; }
        public virtual New_Admission New_Admission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OralSensoryProcessing_OT2> OralSensoryProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration_OT2> Registration_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seeking_OT2> Seeking_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sensitivity_OT2> Sensitivity_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialEmotionalProcessing_OT2> SocialEmotionalProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouchProcessing_OT2> TouchProcessing_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisualProcessing_OT2> VisualProcessing_OT2 { get; set; }
    }
}
