//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationalTherapy1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OccupationalTherapy1()
        {
            this.OT1_Page1 = new HashSet<OT1_Page1>();
            this.OT1_Page2 = new HashSet<OT1_Page2>();
            this.OT1_Page3 = new HashSet<OT1_Page3>();
        }
    
        public int OT1_ID { get; set; }
        public int GR_NO { get; set; }
        public Nullable<System.DateTime> Date_of_Assessment { get; set; }
    
        public virtual New_Admission New_Admission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT1_Page1> OT1_Page1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT1_Page2> OT1_Page2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT1_Page3> OT1_Page3 { get; set; }
    }
}
