//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OralSensoryProcessing_OT2
    {
        public int OralSensoryProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string Item_43 { get; set; }
        public string SN_44 { get; set; }
        public string SN_45 { get; set; }
        public string SN_46 { get; set; }
        public string SN_47 { get; set; }
        public string SK_48 { get; set; }
        public string SK_49 { get; set; }
        public string SK_50 { get; set; }
        public string SK_51 { get; set; }
        public string SN_52 { get; set; }
        public Nullable<int> Oral_Sensory_Raw_Score { get; set; }
        public string Oral_Sensory_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
