//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT1_Page1
    {
        public int Info_ID { get; set; }
        public int OT1_ID { get; set; }
        public string Alertness { get; set; }
        public string Tone { get; set; }
        public string Reflexes { get; set; }
        public string Startle { get; set; }
        public string ATNR { get; set; }
        public string Gallant { get; set; }
        public string Landau { get; set; }
        public string Grasp { get; set; }
        public string Placing { get; set; }
        public string Parachute { get; set; }
    
        public virtual OccupationalTherapy1 OccupationalTherapy1 { get; set; }
    }
}
