//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT1_Page3
    {
        public int Info_ID { get; set; }
        public int OT1_ID { get; set; }
        public string Reach { get; set; }
        public string Prehension { get; set; }
        public string Carry { get; set; }
        public string Release { get; set; }
        public string Isolated { get; set; }
        public string Opposition { get; set; }
        public string TiptoTip { get; set; }
        public string Finger { get; set; }
        public string Pre_writing { get; set; }
        public string Cognition { get; set; }
        public string Auditory { get; set; }
        public string Visual { get; set; }
        public string Taste_Smell { get; set; }
        public string Vestibular { get; set; }
        public string Praxis { get; set; }
        public string Stereignosis { get; set; }
        public string Communication { get; set; }
        public string Behaviour { get; set; }
        public string Sleep { get; set; }
        public string Activities { get; set; }
    
        public virtual OccupationalTherapy1 OccupationalTherapy1 { get; set; }
    }
}
