//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT1_Page2
    {
        public int Info_ID { get; set; }
        public int OT1_ID { get; set; }
        public string Remark_3_Months { get; set; }
        public string Remark_6_Months { get; set; }
        public string Remark_7_Months { get; set; }
        public string Remark_6_To_7_Months { get; set; }
        public string Remark_8_To_10_Months { get; set; }
        public string Remark_10_To_11_Months_Crawl { get; set; }
        public string Remark_9_Months { get; set; }
        public string Remark_10_To_11_Months_Stands { get; set; }
        public string Remark_12_Months_Walks { get; set; }
        public string Remark_13_Months_Walks { get; set; }
        public string Remark_12_Months_Says { get; set; }
        public string Remark_15_To_18_Months_Joints { get; set; }
        public string Remark_13_Months_Feeds { get; set; }
        public string Remark_15_To_18_Months_Climb_Stairs { get; set; }
        public string Remark_2_To_3_Years { get; set; }
        public string Remark_3_To_4_Years { get; set; }
    
        public virtual OccupationalTherapy1 OccupationalTherapy1 { get; set; }
    }
}
