//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentLevel_IEP
    {
        public int PresentLevel_ID { get; set; }
        public int IEPlan_ID { get; set; }
        public string Physical_Development { get; set; }
        public string Communication { get; set; }
        public string Self_Help_Skills { get; set; }
        public string Cognition { get; set; }
        public string Socialization { get; set; }
        public string Functional_Academic { get; set; }
        public string Academic_Performance { get; set; }
        public string PreVocational_Skills { get; set; }
        public string Others { get; set; }
    
        public virtual IEPlan IEPlan { get; set; }
    }
}
