//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychologicalAssessment
    {
        public int PA_ID { get; set; }
        public int GR_NO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Solosson_Intelligence_Test { get; set; }
        public Nullable<bool> Draw_A_Person_Test { get; set; }
        public Nullable<bool> Colored_Progressive_Matrices { get; set; }
        public Nullable<bool> Standard_Progressive_Matrices { get; set; }
        public Nullable<bool> Vineland_Adaptive_Behavior_Scales { get; set; }
        public Nullable<bool> Childhood_Autism_Rating_Scale { get; set; }
        public Nullable<bool> Attention_Deficit_Hyperactive_Disorder_Test { get; set; }
        public Nullable<bool> Children_Apperception_Thematic_Test { get; set; }
        public Nullable<bool> Personality_Assessment { get; set; }
    
        public virtual New_Admission New_Admission { get; set; }
    }
}
