//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_OT2
    {
        public int RegistrationOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string Raw_Score_8 { get; set; }
        public string Raw_Score_12 { get; set; }
        public string Raw_Score_23 { get; set; }
        public string Raw_Score_24 { get; set; }
        public string Raw_Score_26 { get; set; }
        public string Raw_Score_33 { get; set; }
        public string Raw_Score_34 { get; set; }
        public string Raw_Score_35 { get; set; }
        public string Raw_Score_36 { get; set; }
        public string Raw_Score_37 { get; set; }
        public string Raw_Score_38 { get; set; }
        public string Raw_Score_39 { get; set; }
        public string Raw_Score_40 { get; set; }
        public string Raw_Score_53 { get; set; }
        public string Raw_Score_54 { get; set; }
        public string Raw_Score_57 { get; set; }
        public string Raw_Score_62 { get; set; }
        public string Raw_Score_76 { get; set; }
        public string Raw_Score_79 { get; set; }
        public string Raw_Score_80 { get; set; }
        public string Raw_Score_85 { get; set; }
        public string Raw_Score_86 { get; set; }
        public Nullable<int> Registration_Score { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
