//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeking_OT2
    {
        public int SeekingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string Raw_Score_14 { get; set; }
        public string Raw_Score_21 { get; set; }
        public string Raw_Score_22 { get; set; }
        public string Raw_Score_25 { get; set; }
        public string Raw_Score_27 { get; set; }
        public string Raw_Score_28 { get; set; }
        public string Raw_Score_30 { get; set; }
        public string Raw_Score_31 { get; set; }
        public string Raw_Score_32 { get; set; }
        public string Raw_Score_41 { get; set; }
        public string Raw_Score_48 { get; set; }
        public string Raw_Score_49 { get; set; }
        public string Raw_Score_50 { get; set; }
        public string Raw_Score_51 { get; set; }
        public string Raw_Score_55 { get; set; }
        public string Raw_Score_56 { get; set; }
        public string Raw_Score_60 { get; set; }
        public string Raw_Score_62 { get; set; }
        public string Raw_Score_63 { get; set; }
        public Nullable<int> Seeking_Score { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
