//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialEmotionalProcessing_OT2
    {
        public int SocialEmotionalProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string RG_62 { get; set; }
        public string AV_63 { get; set; }
        public string AV_64 { get; set; }
        public string AV_65 { get; set; }
        public string AV_66 { get; set; }
        public string AV_67 { get; set; }
        public string AV_68 { get; set; }
        public string SN_69 { get; set; }
        public string AV_70 { get; set; }
        public string AV_71 { get; set; }
        public string AV_72 { get; set; }
        public string SN_73 { get; set; }
        public string AV_74 { get; set; }
        public string AV_75 { get; set; }
        public Nullable<int> Social_Emotional_Score { get; set; }
        public string Social_Emotional_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
