//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouchProcessing_OT2
    {
        public int TouchProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string SN_16 { get; set; }
        public string SN_17 { get; set; }
        public string AV_18 { get; set; }
        public string SN_19 { get; set; }
        public string SN_20 { get; set; }
        public string SK_21 { get; set; }
        public string SK_22 { get; set; }
        public string RG_23 { get; set; }
        public string RG_24 { get; set; }
        public string SK_25 { get; set; }
        public string RG_26 { get; set; }
        public Nullable<int> Touch_Raw_Score { get; set; }
        public string Touch_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
