//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualProcessing_OT2
    {
        public int VisualProcessingOT2_ID { get; set; }
        public int OT2_ID { get; set; }
        public string SN_9 { get; set; }
        public string SN_10 { get; set; }
        public string SN_11 { get; set; }
        public string RG_12 { get; set; }
        public string SN_13 { get; set; }
        public string SK_14 { get; set; }
        public string AV_15 { get; set; }
        public Nullable<int> Visual_Raw_Score { get; set; }
        public string Visual_Comments { get; set; }
    
        public virtual OccupationalTherapy2 OccupationalTherapy2 { get; set; }
    }
}
