//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week4_BT
    {
        public int Week4BT_ID { get; set; }
        public int BT_ID { get; set; }
        public string Throwing_Week4 { get; set; }
        public string Pushing_Week4 { get; set; }
        public string Pinching_Week4 { get; set; }
        public string EyehandCoordination_Week4 { get; set; }
        public string HeadacheComplain_Week4 { get; set; }
        public string Vomiting_Week4 { get; set; }
        public string AttachmentIssue_Week4 { get; set; }
        public string Adjustment_Week4 { get; set; }
        public string Biting_Week4 { get; set; }
        public string HairPulling_Week4 { get; set; }
        public string EatingProblems_Week4 { get; set; }
        public string NoncomplianceBehavior_Week4 { get; set; }
        public string Withdrawn_Week4 { get; set; }
        public string Shyness_Week4 { get; set; }
        public string Tolerance_Week4 { get; set; }
        public string Irritability_Week4 { get; set; }
        public string Unhappy_Week4 { get; set; }
        public string Moodswings_Week4 { get; set; }
        public string Hyperactive_Week4 { get; set; }
        public string Isolation_Week4 { get; set; }
        public string InAttention_Week4 { get; set; }
        public string SustainAttention_Week4 { get; set; }
        public string Restlessness_Week4 { get; set; }
        public string AttentionSeeking_Week4 { get; set; }
        public string Crying_Week4 { get; set; }
        public string Shouting_Week4 { get; set; }
        public string AbusiveLanguage_Week4 { get; set; }
        public string Splitting_Week4 { get; set; }
        public string SelfInjurious_Week4 { get; set; }
        public string PhysicalAggression_Week4 { get; set; }
        public string Other_Week4 { get; set; }
        public string FrequencyBehavior_Week4 { get; set; }
        public string Solution { get; set; }
        public string Remarks { get; set; }
        public string Recommendation { get; set; }
    
        public virtual BehavioralTherapy BehavioralTherapy { get; set; }
    }
}
