//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week2_BT
    {
        public int Week2BT_ID { get; set; }
        public int BT_ID { get; set; }
        public string Throwing_Week2 { get; set; }
        public string Pushing_Week2 { get; set; }
        public string Pinching_Week2 { get; set; }
        public string EyehandCoordination_Week2 { get; set; }
        public string HeadacheComplain_Week2 { get; set; }
        public string Vomiting_Week2 { get; set; }
        public string AttachmentIssue_Week2 { get; set; }
        public string Adjustment_Week2 { get; set; }
        public string Biting_Week2 { get; set; }
        public string HairPulling_Week2 { get; set; }
        public string EatingProblems_Week2 { get; set; }
        public string NoncomplianceBehavior_Week2 { get; set; }
        public string Withdrawn_Week2 { get; set; }
        public string Shyness_Week2 { get; set; }
        public string Tolerance_Week2 { get; set; }
        public string Irritability_Week2 { get; set; }
        public string Unhappy_Week2 { get; set; }
        public string Moodswings_Week2 { get; set; }
        public string Hyperactive_Week2 { get; set; }
        public string Isolation_Week2 { get; set; }
        public string InAttention_Week2 { get; set; }
        public string SustainAttention_Week2 { get; set; }
        public string Restlessness_Week2 { get; set; }
        public string AttentionSeeking_Week2 { get; set; }
        public string Crying_Week2 { get; set; }
        public string Shouting_Week2 { get; set; }
        public string AbusiveLanguage_Week2 { get; set; }
        public string Splitting_Week2 { get; set; }
        public string SelfInjurious_Week2 { get; set; }
        public string PhysicalAggression_Week2 { get; set; }
        public string Other_Week2 { get; set; }
        public string FrequencyBehavior_Week2 { get; set; }
    
        public virtual BehavioralTherapy BehavioralTherapy { get; set; }
    }
}
